require 'rest-client'
require 'yaml'
require 'json'
require 'uri'
require 'configatron'
class JiraBackend


    def initialize
      p configatron.basedir
    end


    def getCollection(path)
      request = RestClient::Request.new(
        :method => :get,
        :url => "#{configatron.plugins.jira.url}/#{path.to_s}",
        :user => configatron.plugins.jira.username,
        :password => configatron.plugins.jira.password,
        :headers => { :accept => :json,
        :content_type => :json }
      )
      response = request.execute

      # puts JSON.pretty_generate(JSON.parse(response.to_str))

      results = JSON.parse(response.to_str)
      
    end

    def postCollection(path, postData)

      request = RestClient::Request.new(
        :method => :post,
        :url => "#{configatron.plugins.jira.url}/#{path.to_s}",
        :user => configatron.plugins.jira.username,
        :password => configatron.plugins.jira.password,
        :headers => { :accept => :json,
        :content_type => :json },
        :payload => postData.to_json
      )
      p request
      puts JSON.pretty_generate(postData)
      response = request.execute
      
      results = JSON.parse(response.to_str)
      
    end


    def getIssue(id)
        getCollection("issue/#{id}")
    end

    def getSearch(queryParams)
        getCollection("search?jql=#{encodeSearchUri(queryParams)}")
    end

    def getIssueStatus(id)
        getIssue(id)['fields']['status']['name']
    end  

    def encodeSearchUri(jqlString)
         URI.escape(jqlString)
    end

    def createIssue(description="autogenerated",summary="autogenerated",labels=[])
        # returns issue key
        issue_template = getJiraIssue(description, summary) 
        issue_template['fields']['labels'] = labels
        postCollection("issue", issue_template )['key']
    end

    def getJiraIssue(description,summary,project=configatron.plugins.jira.project)
        {"fields" => 
            {"project" => 
                {"key" => project }, 
                "summary" => summary, 
                "description" => description, 
                "issuetype" => { "name" => "Taak"},
                "labels" => [],
            }
        }
    end
      
    
  end




